[package]
name = "trex"
version = "0.4.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
nucleo = "0.5"
anyhow = "1.0"
which = "7"
libc = "0.2"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
